name: Deploy Huffle's IT Services Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 🛡️ Harden-Runner for CI/CD security
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      # 🧰 Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 🧪 Optional: Install dependencies (if using a static site generator)
      - name: Install dependencies
        run: |
          npm install

      # 🧱 Build your site (adjust if using Hugo, Jekyll, etc.)
      - name: Build site
        run: |
          npm run build

      # 🚀 Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
